name: ci/cd

on:
  push:
    branches: [ master, release/*, develop]
  pull_request:
    branches: [ master, release/*, develop]

jobs:

  build:
    name: Build on OTP ${{ matrix.otp_version }} / ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        otp_version: [19, 20, 21, 22, 23]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}


    steps:
    - uses: actions/checkout@v2
    - name: Update rebar3
      run: rebar3 local upgrade
    - name: Compile
      run: rebar3 compile
    - name: Run eunit/common tests
      run: rebar3 do eunit, ct
    - name: Run ltest
      run: rebar3 lfe ltest
